name: CI
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: Restaurants.API
      - name: Build
        run: dotnet build --no-restore
        working-directory: Restaurants.API
      - name: Test
        run: dotnet test
        working-directory: Restaurants.API
